apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: exp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exp
  template:
    metadata:
      labels:
        app: exp
    spec:
      containers:
      - name: myapp
        image: mongo-express
        ports:
        - containerPort: 8080
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD   
          value: password
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-service
          
---
apiVersion: v1
kind: Service
metadata: 
  name: express-service
spec:
  selector:
    app: exp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30050