version: "3"
services:
  myapp:
    container_name: myapp
    restart: always
    image: pavancool7/loginform:2.0
    ports:
    - '9090:9999'
    links:
    - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
    - '27017:27017'
    volumes:
    - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
    - '8081:8081'
volumes:
  mongo-data:
    driver: local