apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginform
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: myapp
        image: pavancool7/loginform:1.0
        ports:
        - containerPort: 9999
        env:
##        - name: MONGO_URL
##          value: mongodb://admin:password@myapp
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: password          
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8080
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-service
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata: 
  name: loginform-service
spec:
  selector:
    app: login
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 9999
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
spec:
  selector:
    app: login
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 27017  
---
apiVersion: v1
kind: Service
metadata: 
  name: mongo-express-service
spec:
  selector:
    app: login
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 8080

------------------------------------------------------------------------------------------------------OR_--------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginform
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: myapp
        image: pavancool7/loginform:1.0
        ports:
        - containerPort: 9999
##        env:
##        - name: MONGO_URL
##          value: mongodb://admin:password@myapp
##        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
##          value: admin
##        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
##          value: password          
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8080
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongodb-service
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: admin
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata: 
  name: loginform-service
spec:
  selector:
    app: login
  type: LoadBalancer
  ports:
  - name: loginform
    protocol: TCP
    port: 3031
    targetPort: 9999
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
spec:
  selector:
    app: login
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  - name: mongo-express-service
    protocol: TCP
    port: 8080
    targetPort: 8080



apiVersion: v1
kind: Service
metadata: 
  name: loginform-service
spec:
  selector:
    app: login
  type: LoadBalancer
  ports:
  - name: loginform
    protocol: TCP
    port: 3031
    targetPort: 9999
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
spec:
  selector:
    app: login
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  - name: mongo-express-service
    protocol: TCP
    port: 8080
    targetPort: 8080

